name = "erp"
main = "src/worker2.js"
compatibility_date = "2026-10-01"

[assets]
directory = "./public2"
binding = "ASSETS"
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "nexa-erp"
database_id = "d222d974-6417-46d6-b1a7-c9df31553dd9"

[observability]
enabled = true
