const COOKIE='nexa_erp_session',SESSION_TTL=43200,attempts=new Map();
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=utf-8',...h}}),now=()=>Math.floor(Date.now()/1000);
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''),unb64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function sha256(v){return b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))}
async function pbkdf2(p,e){const [x,it,salt,expected]=(e||'').split('$');if(x!=='pbkdf2'||!it||!salt||!expected)return false;const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:Number(it),hash:'SHA-256'},k,256);return b64(bits)===expected}
async function verifyPassword(p,s){return (s||'').startsWith('pbkdf2$')?pbkdf2(p,s):!!s&&p===s}
function cookie(v,m){return `${COOKIE}=${v}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${m}`}
function getToken(r){const c=r.headers.get('Cookie')||'',m=c.match(new RegExp(`(?:^|;\\s*)${COOKIE}=([^;]+)`));return m?.[1]}
async function requireUser(r,e){if(!e.DB)throw Error('D1 database binding DB is not configured');const t=getToken(r);if(!t)return null;return e.DB.prepare('SELECT s.id,s.user_id,s.expires_at,u.email,u.name,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').bind(await sha256(t),now()).first()}
const sameOrigin=r=>{const o=r.headers.get('Origin');return !o||o===new URL(r.url).origin};
async function login(r,e){const ip=r.headers.get('CF-Connecting-IP')||'unknown',t=now();let a=attempts.get(ip)||{count:0,reset:t+900};if(t>a.reset)a={count:0,reset:t+900};if(a.count>=8)return json({error:'Too many login attempts. Try again later.'},429);const b=await r.json(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');let user=null;
if(email===String(e.ADMIN_EMAIL||'').trim().toLowerCase()&&await verifyPassword(password,e.ADMIN_PASSWORD_HASH)){user={id:'admin',email,name:'System Administrator',role:'admin',active:1};if(e.DB){const existing=await e.DB.prepare('SELECT id FROM users WHERE id=?').bind('admin').first();if(!existing)await e.DB.prepare('INSERT INTO users(id,email,name,password_hash,role,active,created_at) VALUES(?,?,?,?,?,1,?)').bind('admin',email,'System Administrator',e.ADMIN_PASSWORD_HASH,'admin',1,now()).run();}}
else if(e.DB){user=await e.DB.prepare('SELECT * FROM users WHERE lower(email)=? AND active=1').bind(email).first();if(!user||!(await verifyPassword(password,user.password_hash)))user=null}
if(!user){a.count++;attempts.set(ip,a);return json({error:'Invalid email or password'},401)}attempts.delete(ip);const token=b64(crypto.getRandomValues(new Uint8Array(32))),hash=await sha256(token),expires=t+SESSION_TTL;await e.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at,ip) VALUES(?,?,?,?,?)').bind(hash,String(user.id),expires,t,ip).run();return json({user:{id:user.id,email:user.email,name:user.name,role:user.role}},200,{'Set-Cookie':cookie(token,SESSION_TTL)})}
async function api(r,e,c){const u=new URL(r.url),p=u.pathname;if(r.method==='POST'&&p==='/api/login')return login(r,e);if(p==='/api/fx'&&r.method==='GET'){const base=(u.searchParams.get('base')||'INR').toUpperCase(),ck=new Request(`https://fx.internal/${base}`),cache=caches.default,hit=await cache.match(ck);if(hit)return hit;const up=await fetch(`https://open.er-api.com/v6/latest/${encodeURIComponent(base)}`,{cf:{cacheTtl:300,cacheEverything:true}});if(!up.ok)return json({error:'Exchange-rate provider unavailable'},502);const d=await up.json(),out=json({base:d.base_code||base,rates:d.rates||{},updated_at:d.time_last_update_utc||null});c.waitUntil(cache.put(ck,out.clone()));return out}if(p==='/api/health')return json({ok:true,time:new Date().toISOString(),d1:!!e.DB});const user=await requireUser(r,e);if(!user)return json({error:'Authentication required'},401);if(r.method!=='GET'&&!sameOrigin(r))return json({error:'Invalid origin'},403);if(p==='/api/me')return json({user:{id:user.user_id,email:user.email,name:user.name,role:user.role}});if(p==='/api/logout'){await e.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(getToken(r))).run();return json({ok:true},200,{'Set-Cookie':cookie('',0)})}
if(p==='/api/users'&&r.method==='GET'){if(user.role!=='admin')return json({error:'Admin only'},403);return json({data:(await e.DB.prepare('SELECT id,email,name,role,active,created_at FROM users ORDER BY created_at DESC').all()).results})}
if(p==='/api/users'&&r.method==='POST'){if(user.role!=='admin')return json({error:'Admin only'},403);const b=await r.json(),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),password=String(b.password||''),role=['admin','manager','operator','viewer'].includes(b.role)?b.role:'operator';if(!email||!password||password.length<12)return json({error:'Email and password are required; password must be at least 12 characters.'},400);const salt=b64(crypto.getRandomValues(new Uint8Array(16))),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:210000,hash:'SHA-256'},key,256),hash=`pbkdf2$210000$${salt}$${b64(bits)}`,id=crypto.randomUUID();try{await e.DB.prepare('INSERT INTO users(id,email,name,password_hash,role,active,created_at) VALUES(?,?,?,?,?,1,?)').bind(id,email,name,hash,role,now()).run()}catch{return json({error:'Unable to create user. Email may already exist.'},409)}return json({ok:true,id})}
const m=p.match(/^\/api\/(banks|customers|products|contracts|shipments|invoices)$/);if(m){const table=m[1],allowed={banks:['name','account','branch','swift'],customers:['company','contact','email','phone','address','importer_bank'],products:['code','name','description','unit','hs_code'],contracts:['contract_no','customer_id','currency','amount','incoterm','payment_method','shipment_destination','last_shipment_date','status'],shipments:['contract_id','mode','origin','destination','eta','status'],invoices:['contract_id','invoice_no','currency','amount','status']}[table];if(r.method==='GET')return json({data:(await e.DB.prepare(`SELECT * FROM ${table} ORDER BY created_at DESC LIMIT 500`).all()).results});if(!['admin','manager','operator'].includes(user.role))return json({error:'Write permission denied'},403);const b=await r.json(),keys=allowed.filter(k=>b[k]!==undefined);if(!keys.length)return json({error:'No fields supplied'},400);const id=crypto.randomUUID(),vals=keys.map(k=>b[k]),sql=`INSERT INTO ${table}(id,${keys.join(',')},created_at,updated_at) VALUES(?,${keys.map(()=>'?').join(',')},?,?)`;await e.DB.prepare(sql).bind(id,...vals,now(),now()).run();return json({ok:true,id})}return json({error:'Not found'},404)}
export default{async fetch(r,e,c){const u=new URL(r.url);if(u.pathname.startsWith('/api/'))try{return await api(r,e,c)}catch(err){return json({error:err.message||'Server error'},500)}return e.ASSETS.fetch(r)}};
