const COOKIE='nexa_erp_session',SESSION_TTL=43200,attempts=new Map();
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=utf-8',...h}}),now=()=>Math.floor(Date.now()/1000);
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''),unb64=s=>{let x=s.replace(/-/g,'+').replace(/_/g,'/');x+='='.repeat((4-x.length%4)%4);return Uint8Array.from(atob(x),c=>c.charCodeAt(0))};
async function sha256(v){return b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))}
async function pbkdf2(p,e){const parts=String(e||'').split('$');if(parts.length!==4||parts[0]!=='pbkdf2')return false;const it=Number(parts[1]);if(!Number.isInteger(it)||it<1000||it>10000000)return false;let salt;try{salt=unb64(parts[2])}catch{return false}const expected=parts[3];if(!expected)return false;const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:it,hash:'SHA-256'},k,256);return b64(bits)===expected}
async function verifyPassword(p,s){s=String(s||'');if(s.startsWith('pbkdf2$'))return pbkdf2(p,s);return !!s&&p===s}
function cookie(v,m){return `${COOKIE}=${v}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${m}`}
function getToken(r){const c=r.headers.get('Cookie')||'',m=c.match(new RegExp(`(?:^|;\\s*)${COOKIE}=([^;]+)`));return m?.[1]}
async function requireUser(r,e){if(!e.DB)throw Error('D1 database binding DB is not configured');const t=getToken(r);if(!t)return null;return e.DB.prepare('SELECT s.id,s.user_id,s.expires_at,u.email,u.name,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').bind(await sha256(t),now()).first()}
const sameOrigin=r=>{const o=r.headers.get('Origin');return !o||o===new URL(r.url).origin};
const adminOnly=u=>u.role==='admin';
async function login(r,e){const ip=r.headers.get('CF-Connecting-IP')||'unknown',t=now();let a=attempts.get(ip)||{count:0,reset:t+900};if(t>a.reset)a={count:0,reset:t+900};if(a.count>=8)return json({error:'Too many login attempts. Try again later.'},429);const b=await r.json(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');let user=null;const adminEmail=String(e.ADMIN_EMAIL||'').trim().toLowerCase(),adminSecret=String(e.ADMIN_PASSWORD_HASH||'');if(adminEmail&&adminSecret&&email===adminEmail&&await verifyPassword(password,adminSecret)){user={id:'admin',email:adminEmail,name:'System Administrator',role:'admin',active:1};if(e.DB){await e.DB.prepare('INSERT INTO users(id,email,name,password_hash,role,active,created_at) VALUES(?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,password_hash=excluded.password_hash,role=excluded.role,active=1').bind('admin',adminEmail,'System Administrator',adminSecret,'admin',now()).run();}}else if(e.DB){user=await e.DB.prepare('SELECT * FROM users WHERE lower(email)=? AND active=1').bind(email).first();if(!user||!(await verifyPassword(password,user.password_hash)))user=null}if(!user){a.count++;attempts.set(ip,a);return json({error:'Invalid email or password'},401)}attempts.delete(ip);const token=b64(crypto.getRandomValues(new Uint8Array(32))),hash=await sha256(token),expires=t+SESSION_TTL;await e.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at,ip) VALUES(?,?,?,?,?)').bind(hash,String(user.id),expires,t,ip).run();return json({user:{id:user.id,email:user.email,name:user.name,role:user.role}},200,{'Set-Cookie':cookie(token,SESSION_TTL)})}
const tableMap={banks:['name','account','branch','swift'],customers:['company','contact','email','phone','address','importer_bank'],products:['code','name','description','unit','hs_code'],contracts:['contract_no','customer_id','currency','amount','incoterm','payment_method','shipment_destination','last_shipment_date','status'],shipments:['contract_id','mode','origin','destination','eta','status'],invoices:['contract_id','invoice_no','currency','amount','status']};
async function crud(r,e,u,table){const allowed=tableMap[table];if(r.method==='GET')return json({data:(await e.DB.prepare(`SELECT * FROM ${table} ORDER BY created_at DESC LIMIT 500`).all()).results});if(!['admin','manager','operator'].includes(u.role))return json({error:'Write permission denied'},403);const b=await r.json(),keys=allowed.filter(k=>b[k]!==undefined);if(!keys.length)return json({error:'No fields supplied'},400);const id=crypto.randomUUID(),vals=keys.map(k=>b[k]),sql=`INSERT INTO ${table}(id,${keys.join(',')},created_at,updated_at) VALUES(?,${keys.map(()=>'?').join(',')},?,?)`;await e.DB.prepare(sql).bind(id,...vals,now(),now()).run();return json({ok:true,id})}
async function api(r,e,c){const u=new URL(r.url),p=u.pathname;if(r.method==='POST'&&p==='/api/login')return login(r,e);if(p==='/api/fx'&&r.method==='GET'){const base=(u.searchParams.get('base')||'INR').toUpperCase(),ck=new Request(`https://fx.internal/${base}`),cache=caches.default,hit=await cache.match(ck);if(hit)return hit;const up=await fetch(`https://open.er-api.com/v6/latest/${encodeURIComponent(base)}`,{cf:{cacheTtl:300,cacheEverything:true}});if(!up.ok)return json({error:'Exchange-rate provider unavailable'},502);const d=await up.json(),out=json({base:d.base_code||base,rates:d.rates||{},updated_at:d.time_last_update_utc||null});c.waitUntil(cache.put(ck,out.clone()));return out}if(p==='/api/health')return json({ok:true,time:new Date().toISOString(),d1:!!e.DB,admin_email_configured:!!String(e.ADMIN_EMAIL||'').trim(),admin_password_hash_configured:!!String(e.ADMIN_PASSWORD_HASH||'').trim(),admin_hash_format:String(e.ADMIN_PASSWORD_HASH||'').startsWith('pbkdf2$')?'pbkdf2':(String(e.ADMIN_PASSWORD_HASH||'')?'legacy':'missing')});const user=await requireUser(r,e);if(!user)return json({error:'Authentication required'},401);if(r.method!=='GET'&&!sameOrigin(r))return json({error:'Invalid origin'},403);if(p==='/api/me')return json({user:{id:user.user_id,email:user.email,name:user.name,role:user.role}});if(p==='/api/logout'){await e.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(getToken(r))).run();return json({ok:true},200,{'Set-Cookie':cookie('',0)})}
if(p==='/api/users'&&r.method==='GET'){if(!adminOnly(user))return json({error:'Admin only'},403);return json({data:(await e.DB.prepare('SELECT id,email,name,role,active,created_at FROM users ORDER BY created_at DESC').all()).results})}
if(p==='/api/users'&&r.method==='POST'){if(!adminOnly(user))return json({error:'Admin only'},403);const b=await r.json(),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),password=String(b.password||''),role=['admin','manager','operator','viewer'].includes(b.role)?b.role:'operator';if(!email||!password||password.length<12)return json({error:'Email and password are required; password must be at least 12 characters.'},400);const salt=b64(crypto.getRandomValues(new Uint8Array(16))),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:210000,hash:'SHA-256'},key,256),hash=`pbkdf2$210000$${salt}$${b64(bits)}`,id=crypto.randomUUID();try{await e.DB.prepare('INSERT INTO users(id,email,name,password_hash,role,active,created_at) VALUES(?,?,?,?,?,1,?)').bind(id,email,name,hash,role,now()).run()}catch{return json({error:'Unable to create user. Email may already exist.'},409)}return json({ok:true,id})}
if(p==='/api/companies'&&r.method==='GET')return json({data:(await e.DB.prepare('SELECT * FROM companies ORDER BY created_at DESC').all()).results});
if(p==='/api/companies'&&r.method==='POST'){if(!adminOnly(user))return json({error:'Admin only'},403);const b=await r.json(),id=crypto.randomUUID(),t=now();await e.DB.prepare('INSERT INTO companies(id,legal_name,trade_name,pan,tan,cin,constitution,registered_address,email,phone,website,financial_year_start,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,String(b.legal_name||''),b.trade_name||null,b.pan||null,b.tan||null,b.cin||null,b.constitution||null,b.registered_address||null,b.email||null,b.phone||null,b.website||null,b.financial_year_start||'04-01',t,t).run();return json({ok:true,id})}
if(p==='/api/branches'&&r.method==='GET')return json({data:(await e.DB.prepare('SELECT b.*,c.legal_name AS company_name FROM branches b JOIN companies c ON c.id=b.company_id ORDER BY b.created_at DESC').all()).results});
if(p==='/api/branches'&&r.method==='POST'){if(!['admin','manager'].includes(user.role))return json({error:'Management permission required'},403);const b=await r.json(),id=crypto.randomUUID(),t=now();await e.DB.prepare('INSERT INTO branches(id,company_id,code,name,address,city,state,state_code,pincode,email,phone,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,b.company_id,b.code,b.name,b.address||null,b.city||null,b.state||null,b.state_code||null,b.pincode||null,b.email||null,b.phone||null,b.active===0?0:1,t,t).run();return json({ok:true,id})}
if(p==='/api/registrations'&&r.method==='GET')return json({data:(await e.DB.prepare('SELECT r.*,c.legal_name AS company_name,b.name AS branch_name FROM registrations r JOIN companies c ON c.id=r.company_id LEFT JOIN branches b ON b.id=r.branch_id ORDER BY r.created_at DESC').all()).results});
if(p==='/api/registrations'&&r.method==='POST'){if(!['admin','manager'].includes(user.role))return json({error:'Management permission required'},403);const b=await r.json(),id=crypto.randomUUID(),t=now();await e.DB.prepare('INSERT INTO registrations(id,company_id,branch_id,registration_type,registration_number,registration_date,expiry_date,status,issuing_authority,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,b.company_id,b.branch_id||null,b.registration_type,b.registration_number,b.registration_date||null,b.expiry_date||null,b.status||'active',b.issuing_authority||null,b.notes||null,t,t).run();return json({ok:true,id})}
if(p==='/api/tax-periods'&&r.method==='GET'){const company=u.searchParams.get('company_id');const q=company?'SELECT * FROM tax_periods WHERE company_id=? ORDER BY created_at DESC':'SELECT * FROM tax_periods ORDER BY created_at DESC';return json({data:(await e.DB.prepare(q).bind(...(company?[company]:[])).all()).results})}
if(p==='/api/tax-periods'&&r.method==='POST'){if(!['admin','manager','operator'].includes(user.role))return json({error:'Tax filing permission denied'},403);const b=await r.json(),id=crypto.randomUUID(),t=now();await e.DB.prepare('INSERT INTO tax_periods(id,company_id,financial_year,period,return_type,status,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,b.company_id,b.financial_year,b.period,b.return_type,b.status||'draft',JSON.stringify(b.payload||{}),t,t).run();return json({ok:true,id})}
if(p==='/api/compliance/gst-json'&&r.method==='POST'){if(!['admin','manager','operator'].includes(user.role))return json({error:'Tax filing permission denied'},403);const b=await r.json();const payload={schema_version:'1.0',return_type:b.return_type||'GSTR1',financial_year:b.financial_year||'',period:b.period||'',gstin:b.gstin||'',legal_name:b.legal_name||'',branch_gstin:b.branch_gstin||'',generated_at:new Date().toISOString(),invoices:b.invoices||[],credit_debit_notes:b.credit_debit_notes||[],hsn_summary:b.hsn_summary||[],nil_rated:b.nil_rated||[]};return json({filename:`GST_${payload.return_type}_${payload.period||'period'}.json`,portal_ready:false,notice:'This is an ERP-generated JSON working file. Validate against the current GST portal schema before filing.',payload})}
if(p==='/api/compliance/itr-json'&&r.method==='POST'){if(!['admin','manager','operator'].includes(user.role))return json({error:'Tax filing permission denied'},403);const b=await r.json();const payload={schema_version:'1.0',assessment_year:b.assessment_year||'',return_form:b.return_form||'',pan:b.pan||'',legal_name:b.legal_name||'',residential_or_registered_address:b.address||'',business_income:b.business_income||{},capital_gains:b.capital_gains||{},other_income:b.other_income||{},deductions:b.deductions||{},taxes_paid:b.taxes_paid||{},assets_liabilities:b.assets_liabilities||{},generated_at:new Date().toISOString()};return json({filename:`ITR_${payload.return_form||'return'}_${payload.assessment_year||'AY'}.json`,portal_ready:false,notice:'This is an ERP-generated JSON working file. Validate and transform it using the current Income Tax Department schema/utilities before filing.',payload})}
const m=p.match(/^\/api\/(banks|customers|products|contracts|shipments|invoices)$/);if(m)return crud(r,e,user,m[1]);return json({error:'Not found'},404)}
export default{async fetch(r,e,c){const u=new URL(r.url);if(u.pathname.startsWith('/api/'))try{return await api(r,e,c)}catch(err){return json({error:err.message||'Server error'},500)}return e.ASSETS.fetch(r)}};